"""
Question mapper — maps aggregated data to the strategic discovery questions.
Auto-generated by setup_engine.py — edit discovery_config.yaml to change.
"""

from pipeline.quantification.aggregator import Aggregator


# ─────────────────────────────────────────────────────────────
# Question metadata
# ─────────────────────────────────────────────────────────────

QUESTIONS = {
    1:  ("Why do users open the app but abandon their cart before ordering?",               "Cart Abandonment"),
    2:  ("What prevents users from completing their food order?",                           "Order Prevention"),
    3:  ("What uncertainties remain after selecting a restaurant?",                         "Restaurant Uncertainty"),
    4:  ("What causes users to postpone placing an order?",                                 "Order Postponement"),
    5:  ("How do users compare food delivery platforms before ordering?",                   "Platform Comparison"),
    6:  ("What information do users seek outside the app before ordering?",                 "External Info Seeking"),
    7:  ("What role do price, delivery speed, food quality, hygiene, packaging, and restaurant variety play?", "Factor Importance"),
    8:  ("When is the cart genuine order intent vs casual browsing?",                       "Intent vs Browsing"),
    9:  ("How do friction patterns differ across user segments and platforms?",             "Segment Differences"),
    10:  ("What unmet needs emerge consistently across user feedback?",                      "Unmet Needs"),
}

# Which hesitation tags map to each question
QUESTION_TAG_MAPPING = {
    1:  None,
    2:  ["delivery_delay_fear", "price_surge", "food_quality_doubt", "minimum_order_concern", "restaurant_closed", "payment_issue"],
    3:  ["food_quality_doubt", "hygiene_concern", "portion_size_doubt", "delivery_delay_fear"],
    4:  ["price_surge", "waiting_for_offer", "minimum_order_concern", "meal_timing_mismatch"],
    5:  ["competitor_better_offer"],
    6:  None,
    7:  None,
    8:  None,
    9:  None,
    10:  None,
}


def _base(agg: Aggregator, question_id: int, tags=None, quotes_limit: int = 4) -> dict:
    """Build the base schema shared by all question files."""
    q_text, q_short = QUESTIONS[question_id]

    from sqlalchemy import text
    rows = agg._q("""
        SELECT COUNT(*) FROM question_mappings WHERE question_id = :qid
    """, {"qid": question_id})
    total_relevant = int(rows[0][0]) if rows else 0

    breakdown = agg.hesitation_frequency(question_ids=[question_id]) if tags is not False else []

    segment_splits = {
        seg: agg.hesitation_frequency(question_ids=[question_id], segment=seg)
        for seg in ["gen_z", "millennial", "gen_x"]
    } if tags is not False else {}

    source_attribution = agg.hesitation_by_source(question_ids=[question_id]) if tags is not False else []
    quote_tags = tags if tags else None
    key_quotes = agg.key_quotes(tags=quote_tags, limit=quotes_limit)
    temporal_trend = agg.temporal_trend(question_ids=[question_id] if question_id else None)

    avg_conf_rows = agg._q("""
        SELECT AVG(h.confidence) FROM hesitation_tags h
        JOIN question_mappings qm ON h.doc_id = qm.doc_id
        WHERE qm.question_id = :qid
    """, {"qid": question_id})
    avg_conf = round(float(avg_conf_rows[0][0] or 0.70), 3)

    return {
        "question_id":        question_id,
        "question_text":      q_text,
        "question_short":     q_short,
        "total_relevant_docs": total_relevant,
        "avg_confidence":     avg_conf,
        "breakdown":          breakdown,
        "segment_splits":     segment_splits,
        "source_attribution": source_attribution,
        "key_quotes":         key_quotes,
        "temporal_trend":     temporal_trend,
    }


def build_all_questions(agg: Aggregator) -> dict:
    """Build all question data objects. Returns {1: data, 2: data, ...}"""
    results = {}
    for qid in QUESTIONS:
        try:
            data = _base(agg, qid)
            results[qid] = data
            print(f"    [OK] Q{qid}: {QUESTIONS[qid][1]}")
        except Exception as e:
            print(f"    [!!] Q{qid} failed: {e}")
            results[qid] = {
                "question_id":   qid,
                "question_text": QUESTIONS[qid][0],
                "question_short": QUESTIONS[qid][1],
                "error":         str(e),
            }
    return results
