"""
Scraper configurations for Swiggy Discovery Engine.
Auto-generated by setup_engine.py — edit discovery_config.yaml to change.
"""

# ──────────────────────────────────────────────────────────
# Playstore
# ──────────────────────────────────────────────────────────
PLAYSTORE_CONFIG = {
    "app_id": "in.swiggy.android",
    "lang": "en",
    "country": "in",
    "sort": 1,
    "count": 50000,
    "batch_size": 200,
    "checkpoint_every": 5000,
}

# ──────────────────────────────────────────────────────────
# Appstore
# ──────────────────────────────────────────────────────────
APPSTORE_CONFIG = {
    "app_id": "989540920",
    "country": "in",
    "rss_url": "https://itunes.apple.com/in/rss/customerreviews/id=989540920/sortBy=mostRecent/json",
    "max_pages": 50,
    "target_count": 10000,
}

# ──────────────────────────────────────────────────────────
# Reddit
# ──────────────────────────────────────────────────────────
REDDIT_CONFIG = {
    "subreddits": [
        "swiggy",
        "india",
        "bangalore",
        "mumbai",
        "delhi",
        "hyderabad",
        "pune"
],
    "search_queries": [
        "swiggy delivery",
        "swiggy complaint",
        "swiggy vs zomato",
        "swiggy order issue",
        "swiggy refund",
        "swiggy customer care",
        "food delivery app india",
        "swiggy review"
],
    "sort": "relevance",
    "time_filter": "all",
    "limit_per_query": 500,
    "include_comments": True,
    "comment_depth": 5,
    "min_upvotes": 1,
}

# ──────────────────────────────────────────────────────────
# Youtube
# ──────────────────────────────────────────────────────────
YOUTUBE_CONFIG = {
    "search_queries": [
        "swiggy review",
        "swiggy experience",
        "swiggy vs zomato",
        "swiggy food quality",
        "swiggy delivery late",
        "swiggy dark kitchen",
        "food delivery experience india"
],
    "max_videos_per_query": 30,
    "max_comments_per_video": 200,
    "order": "relevance",
    "published_after": "2022-01-01T00:00:00Z",
    "region_code": "IN",
    "relevance_language": "en",
    "comment_order": "relevance",
}

# ──────────────────────────────────────────────────────────
# Trustpilot
# ──────────────────────────────────────────────────────────
TRUSTPILOT_CONFIG = {
    "base_url": "https://www.trustpilot.com/review/www.swiggy.com",
    "max_pages": 100,
    "target_count": 5000,
    "wait_between_pages": 2,
}

# ──────────────────────────────────────────────────────────
# Pissedconsumer
# ──────────────────────────────────────────────────────────
PISSEDCONSUMER_CONFIG = {
    "base_url": "https://swiggy.pissedconsumer.com/review.html",
    "max_pages": 50,
    "target_count": 3000,
    "wait_between_pages": 2,
}

# ──────────────────────────────────────────────────────────
# Aggregate config
# ──────────────────────────────────────────────────────────
SCRAPER_CONFIGS = {
    "playstore": PLAYSTORE_CONFIG,
    "appstore": APPSTORE_CONFIG,
    "reddit": REDDIT_CONFIG,
    "youtube": YOUTUBE_CONFIG,
    "trustpilot": TRUSTPILOT_CONFIG,
    "pissedconsumer": PISSEDCONSUMER_CONFIG,
}

VALID_SOURCES = {'playstore', 'appstore', 'reddit', 'youtube', 'trustpilot', 'pissedconsumer'}
PRIMARY_SOURCES = {'appstore', 'playstore', 'reddit', 'youtube'}
SECONDARY_SOURCES = {'pissedconsumer', 'trustpilot'}
