"""
Relevance filter — keeps documents that contain domain-relevant signals.
Auto-generated by setup_engine.py — edit discovery_config.yaml to change.
"""

import re
from typing import List, Tuple


# Keywords that indicate domain relevance
DOMAIN_KEYWORDS = {
    "swiggy",
    "zomato",
    "food delivery",
    "food order",
    "uber eats",
    "dunzo",
    "restaurant",
    "food",
    "meal",
    "order",
    "delivery",
    "deliver",
    "biryani",
    "pizza",
    "burger",
    "thali",
    "menu",
    "cuisine",
    "kitchen",
    "chef",
    "cart",
    "checkout",
    "payment",
    "cod",
    "delivery boy",
    "delivery partner",
    "rider",
    "coupon",
    "discount",
    "offer",
    "promo",
    "minimum order",
    "surge",
    "refund",
    "cancel",
    "fresh",
    "stale",
    "cold food",
    "spill",
    "packaging",
    "hygiene",
    "taste",
    "portion",
    "quantity",
    "khana",
    "khaana",
    "order kiya",
    "delivery nahi",
    "refund nahi",
    "ghatiya",
    "bekar",
    "accha",
}

# Noise patterns (ultra-short or non-informative)
NOISE_PATTERNS = [
    r"^\s*(good|nice|bad|worst|best|ok|okay|fine|great|excellent|awesome|terrible|horrible|amazing)\s*[.!]*\s*$",
    r"^[⭐★☆✩✪]+\s*$",
    r"^\s*\d+\s*$",
]

NOISE_REGEXES = [re.compile(p, re.IGNORECASE) for p in NOISE_PATTERNS]

MIN_WORD_COUNT = 4

# Sources where ALL reviews are inherently relevant
AUTO_RELEVANT_SOURCES = ("playstore", "appstore", "trustpilot", "pissedconsumer", "reviewsio")


def is_relevant(text: str) -> bool:
    """Check if text is relevant to the domain."""
    if not text:
        return False
    text_lower = text.lower()
    words = text_lower.split()
    if len(words) < MIN_WORD_COUNT:
        return False
    for regex in NOISE_REGEXES:
        if regex.match(text):
            return False
    for keyword in DOMAIN_KEYWORDS:
        if keyword in text_lower:
            return True
    return False


def is_relevant_with_source(text: str, source: str) -> bool:
    """Check relevance with source context."""
    if not text or len(text.split()) < MIN_WORD_COUNT:
        return False
    for regex in NOISE_REGEXES:
        if regex.match(text):
            return False
    if source in AUTO_RELEVANT_SOURCES:
        return True
    return is_relevant(text)


def filter_documents(docs: List[dict]) -> Tuple[List[dict], int]:
    """Filter documents for relevance. Returns (relevant_docs, dropped_count)."""
    kept = []
    dropped = 0
    for doc in docs:
        content = doc.get("content", "")
        source = doc.get("source", "")
        if is_relevant_with_source(content, source):
            kept.append(doc)
        else:
            dropped += 1
    return kept, dropped
