// constants.ts — question metadata, color palette, source colors
// Auto-generated by setup_engine.py — edit discovery_config.yaml to change.

export interface QuestionMeta {
  text: string;
  short: string;
  color: string;
  sourceType: 'primary' | 'secondary' | 'both';
  sourceLabel: string;
  sourceDetail: string;
}

export const QUESTION_META: Record<number, QuestionMeta> = {
  1: {
    text: 'Why do users open the app but abandon their cart before ordering?',
    short: 'Cart Abandonment',
    color: '#ff3f6c',
    sourceType: 'both',
    sourceLabel: 'All Sources',
    sourceDetail: 'Auto-generated from discovery config.',
  },  2: {
    text: 'What prevents users from completing their food order?',
    short: 'Order Prevention',
    color: '#ff7849',
    sourceType: 'both',
    sourceLabel: 'All Sources',
    sourceDetail: 'Auto-generated from discovery config.',
  },  3: {
    text: 'What uncertainties remain after selecting a restaurant?',
    short: 'Restaurant Uncertainty',
    color: '#a855f7',
    sourceType: 'both',
    sourceLabel: 'All Sources',
    sourceDetail: 'Auto-generated from discovery config.',
  },  4: {
    text: 'What causes users to postpone placing an order?',
    short: 'Order Postponement',
    color: '#2dd4bf',
    sourceType: 'both',
    sourceLabel: 'All Sources',
    sourceDetail: 'Auto-generated from discovery config.',
  },  5: {
    text: 'How do users compare food delivery platforms before ordering?',
    short: 'Platform Comparison',
    color: '#3b82f6',
    sourceType: 'both',
    sourceLabel: 'All Sources',
    sourceDetail: 'Auto-generated from discovery config.',
  },  6: {
    text: 'What information do users seek outside the app before ordering?',
    short: 'External Info Seeking',
    color: '#fbbf24',
    sourceType: 'both',
    sourceLabel: 'All Sources',
    sourceDetail: 'Auto-generated from discovery config.',
  },  7: {
    text: 'What role do price, delivery speed, food quality, hygiene, packaging, and restaurant variety play?',
    short: 'Factor Importance',
    color: '#ec4899',
    sourceType: 'both',
    sourceLabel: 'All Sources',
    sourceDetail: 'Auto-generated from discovery config.',
  },  8: {
    text: 'When is the cart genuine order intent vs casual browsing?',
    short: 'Intent vs Browsing',
    color: '#84cc16',
    sourceType: 'both',
    sourceLabel: 'All Sources',
    sourceDetail: 'Auto-generated from discovery config.',
  },  9: {
    text: 'How do friction patterns differ across user segments and platforms?',
    short: 'Segment Differences',
    color: '#f97316',
    sourceType: 'both',
    sourceLabel: 'All Sources',
    sourceDetail: 'Auto-generated from discovery config.',
  },  10: {
    text: 'What unmet needs emerge consistently across user feedback?',
    short: 'Unmet Needs',
    color: '#8b5cf6',
    sourceType: 'both',
    sourceLabel: 'All Sources',
    sourceDetail: 'Auto-generated from discovery config.',
  }
};

export const SOURCE_COLORS: Record<string, string> = {
  'Play Store': '#ff3f6c',
  'App Store': '#2dd4bf',
  'Reddit': '#ff7849',
  'YouTube': '#a855f7',
  'Trustpilot': '#3b82f6',
  'PissedConsumer': '#fbbf24',
};

export const CONFIDENCE_THRESHOLDS = {
  high: 0.8,
  mid:  0.6,
} as const;

export const CHART_COLORS = ["#ff3f6c", "#ff7849", "#a855f7", "#2dd4bf", "#3b82f6", "#fbbf24", "#ec4899", "#84cc16", "#f97316", "#8b5cf6"];

export function confBadgeClass(conf: number): 'badge-conf-high' | 'badge-conf-mid' | 'badge-conf-low' {
  if (conf >= CONFIDENCE_THRESHOLDS.high) return 'badge-conf-high';
  if (conf >= CONFIDENCE_THRESHOLDS.mid)  return 'badge-conf-mid';
  return 'badge-conf-low';
}
