// Mock data used during development before real pipeline runs.
// Auto-generated by setup_engine.py — edit discovery_config.yaml to change.

export const MOCK_Q6_SANKEY = {
  nodes: [
    { id: 'Swiggy App' },
    { id: 'YouTube Reviews' },
    { id: 'Reddit Thread' },
    { id: 'Competitor App' },
    { id: 'Instagram/Social' },
    { id: 'Google Search' },
    { id: 'Friend / WhatsApp' },
    { id: 'Ordered ✓' },
    { id: 'Abandoned ✗' },
    { id: 'Still Undecided' },
  ],
  links: [
    { source: 'Swiggy App', target: 'YouTube Reviews', value: 3800 },
    { source: 'Swiggy App', target: 'Reddit Thread', value: 2900 },
    { source: 'Swiggy App', target: 'Competitor App', value: 2100 },
    { source: 'Swiggy App', target: 'Instagram/Social', value: 1700 },
    { source: 'Swiggy App', target: 'Google Search', value: 900 },
    { source: 'Swiggy App', target: 'Friend / WhatsApp', value: 600 },
    { source: 'YouTube Reviews', target: 'Ordered ✓', value: 1900 },
    { source: 'YouTube Reviews', target: 'Abandoned ✗', value: 1100 },
    { source: 'Reddit Thread', target: 'Ordered ✓', value: 1400 },
    { source: 'Reddit Thread', target: 'Abandoned ✗', value: 900 },
    { source: 'Competitor App', target: 'Abandoned ✗', value: 1100 },
    { source: 'Instagram/Social', target: 'Ordered ✓', value: 900 },
    { source: 'Google Search', target: 'Ordered ✓', value: 600 },
    { source: 'Friend / WhatsApp', target: 'Ordered ✓', value: 500 },
  ],
};

export const MOCK_Q9_GROUPED = [
  { factor: 'Delivery Delay Fear', youtube: 74, play_store: 11, reddit: 9, pissed_consumer: 4, app_store: 2 },
  { factor: 'Price Surge', youtube: 42, play_store: 28, reddit: 20, pissed_consumer: 6, app_store: 4 },
  { factor: 'Food Quality Doubt', youtube: 5, play_store: 18, reddit: 12, pissed_consumer: 62, app_store: 3 },
  { factor: 'Hygiene Concern', youtube: 82, play_store: 4, reddit: 11, pissed_consumer: 1, app_store: 2 },
  { factor: 'Minimum Order Concern', youtube: 35, play_store: 25, reddit: 30, pissed_consumer: 8, app_store: 2 },
];

export const MOCK_SUMMARY = {
  generated_at: "2026-01-01T00:00:00Z",
  pipeline_version: "1.0.0",
  kpi_cards: [
    { id: "total_reviews", label: "Reviews Analyzed", value: 8000, unit: "count", sparkline: [4000, 5000, 6000, 7000, 8000] },
    { id: "delivery_delay_fear", label: "Delivery Delay Fear", value: 40.0, unit: "percent", sparkline: [24, 28, 32, 36, 40] },
    { id: "price_surge", label: "Price Surge", value: 14.4, unit: "percent", sparkline: [9, 10, 11, 13, 14] },
    { id: "unmet_needs", label: "Unmet Needs Identified", value: 30, unit: "count", sparkline: [18, 21, 24, 27, 30] },
  ],
  source_distribution: [
    { source: "Play Store", count: 5000, pct: 33.3, color: "#ff3f6c" },\n    { source: "App Store", count: 4000, pct: 26.7, color: "#2dd4bf" },\n    { source: "Reddit", count: 3000, pct: 20.0, color: "#ff7849" },\n    { source: "YouTube", count: 2000, pct: 13.3, color: "#a855f7" },\n    { source: "Trustpilot", count: 1000, pct: 6.7, color: "#3b82f6" }
  ],
  top_opportunities: [
    { rank: 1, label: "Delivery Delay Fear", question_id: 2, pct: 40, count: 3200, avg_confidence: 0.70, impact_score: 10.0 },\n    { rank: 2, label: "Price Surge", question_id: 2, pct: 33, count: 2640, avg_confidence: 0.73, impact_score: 9.3 },\n    { rank: 3, label: "Food Quality Doubt", question_id: 2, pct: 26, count: 2080, avg_confidence: 0.76, impact_score: 8.6 },\n    { rank: 4, label: "Hygiene Concern", question_id: 2, pct: 19, count: 1520, avg_confidence: 0.79, impact_score: 7.9 },\n    { rank: 5, label: "Minimum Order Concern", question_id: 2, pct: 12, count: 960, avg_confidence: 0.82, impact_score: 7.2 }
  ],
  overall_confidence: 0.69,
  primary_signal_docs: 7000,
  secondary_signal_docs: 500,
  no_signal_docs: 0,
};

export const MOCK_Q2 = {
  question_id: 2,
  question_text: "What prevents users from completing their food order?",
  question_short: "Order Prevention",
  total_relevant_docs: 7000,
  avg_confidence: 0.678,
  breakdown: [
    { label: "Delivery Delay Fear", tag: "delivery_delay_fear", count: 3200, pct: 40.0, avg_confidence: 0.57, color: "#ff3f6c" },
    { label: "Price Surge", tag: "price_surge", count: 1150, pct: 14.4, avg_confidence: 0.69, color: "#ff7849" },
  ],
  source_attribution: [],
  key_quotes: [
    { text: "Sample review quote from users.", source: "Play Store", source_id: "gp_001", date: "2026-01-15", confidence: 0.92, tags: ["delivery_delay_fear"] },
  ],
  temporal_trend: [
    { month: "2025-01", count: 300, pct: 29.0 },
    { month: "2025-07", count: 400, pct: 32.5 },
    { month: "2026-01", count: 460, pct: 34.0 },
  ],
};

export const MOCK_SYSTEMIC_GAPS = {
  generated_at: "2026-01-01T00:00:00Z",
  total_secondary_docs: 500,
  issue_breakdown: [
    { label: "Delivery Delay Fear", tag: "delivery_delay_fear", count: 200, pct: 40.0, color: "#ff3f6c" },
    { label: "Price Surge", tag: "price_surge", count: 120, pct: 24.0, color: "#ff7849" },
  ],
  correlation_with_hesitation: [],
  key_quotes: [
    { text: "Sample complaint from secondary source.", source: "PissedConsumer", date: "2026-02-10", issue: "delivery_delay_fear" },
  ],
};

export const QUESTION_META: Record<number, { text: string; short: string }> = {
  1: { text: "Why do users open the app but abandon their cart before ordering?", short: "Cart Abandonment" },\n  2: { text: "What prevents users from completing their food order?", short: "Order Prevention" },\n  3: { text: "What uncertainties remain after selecting a restaurant?", short: "Restaurant Uncertainty" },\n  4: { text: "What causes users to postpone placing an order?", short: "Order Postponement" },\n  5: { text: "How do users compare food delivery platforms before ordering?", short: "Platform Comparison" },\n  6: { text: "What information do users seek outside the app before ordering?", short: "External Info Seeking" },\n  7: { text: "What role do price, delivery speed, food quality, hygiene, packaging, and restaurant variety play?", short: "Factor Importance" },\n  8: { text: "When is the cart genuine order intent vs casual browsing?", short: "Intent vs Browsing" },\n  9: { text: "How do friction patterns differ across user segments and platforms?", short: "Segment Differences" },\n  10: { text: "What unmet needs emerge consistently across user feedback?", short: "Unmet Needs" }
};
