"""
Keyword-based classification tagger.
Auto-generated by setup_engine.py — edit discovery_config.yaml to change.
"""

import re
from typing import List, Dict, Any


# ──────────────────────────────────────────────────────────
# 1. Hesitation Reason Patterns
# ──────────────────────────────────────────────────────────

HESITATION_PATTERNS = {
    "delivery_delay_fear": [
        r"\bdelivery\b", r"\bdelay\b", r"\bfear\b",
    ],
    "price_surge": [
        r"\bprice\b", r"\bsurge\b",
    ],
    "food_quality_doubt": [
        r"\bfood\b", r"\bquality\b", r"\bdoubt\b",
    ],
    "hygiene_concern": [
        r"\bhygiene\b", r"\bconcern\b",
    ],
    "minimum_order_concern": [
        r"\bminimum\b", r"\border\b", r"\bconcern\b",
    ],
    "restaurant_closed": [
        r"\brestaurant\b", r"\bclosed\b",
    ],
    "payment_issue": [
        r"\bpayment\b", r"\bissue\b",
    ],
    "address_issue": [
        r"\baddress\b", r"\bissue\b",
    ],
    "competitor_better_offer": [
        r"\bcompetitor\b", r"\bbetter\b", r"\boffer\b",
    ],
    "portion_size_doubt": [
        r"\bportion\b", r"\bsize\b", r"\bdoubt\b",
    ],
    "waiting_for_offer": [
        r"\bwaiting\b", r"\bfor\b", r"\boffer\b",
    ],
    "meal_timing_mismatch": [
        r"\bmeal\b", r"\btiming\b", r"\bmismatch\b",
    ],
    "trust_deficit": [
        r"\btrust\b", r"\bdeficit\b",
    ],
    "customer_support_issue": [
        r"\bcustomer\b", r"\bsupport\b", r"\bissue\b",
    ],
    "packaging_concern": [
        r"\bpackaging\b", r"\bconcern\b",
    ],
    "other": [
        r"\bother\b",
    ],
}


# ──────────────────────────────────────────────────────────
# 2. Intent Classification Patterns
# ──────────────────────────────────────────────────────────

INTENT_PATTERNS = {
    "genuine_order_intent": [r"\bgenuine\b", r"\border\b", r"\bintent\b"],
    "browsing": [r"\bbrowsing\b"],
    "price_checking": [r"\bprice\b", r"\bchecking\b"],
    "comparison_shortlist": [r"\bcomparison\b", r"\bshortlist\b"],
    "meal_planning": [r"\bmeal\b", r"\bplanning\b"],
    "unknown": [r"\bunknown\b"],
}


# ──────────────────────────────────────────────────────────
# 3. Platform Comparison Patterns
# ──────────────────────────────────────────────────────────

PLATFORM_PATTERNS = {
    "zomato": [r"\bzomato\b"],
    "eatsure": [r"\beatsure\b"],
    "uber_eats": [r"\buber eats\b"],
    "dunzo": [r"\bdunzo\b"],
    "blinkit": [r"\bblinkit\b"],
    "offline_restaurant": [r"\boffline restaurant\b"],
    "other": [r"\bother\b"],
}


# ──────────────────────────────────────────────────────────
# 4. External Info Patterns
# ──────────────────────────────────────────────────────────

INFO_PATTERNS = {
    "youtube_reviews": [r"\byoutube\b", r"\breviews\b"],
    "instagram_food": [r"\binstagram\b", r"\bfood\b"],
    "google_search": [r"\bgoogle\b", r"\bsearch\b"],
    "ask_friends": [r"\bask\b", r"\bfriends\b"],
    "google_maps_reviews": [r"\bgoogle\b", r"\bmaps\b", r"\breviews\b"],
    "food_blogger": [r"\bfood\b", r"\bblogger\b"],
    "other": [r"\bother\b"],
}


# ──────────────────────────────────────────────────────────
# 5. Factor Patterns
# ──────────────────────────────────────────────────────────

FACTOR_PATTERNS = {
    "delivery_speed": [r"\bdelivery\b", r"\bspeed\b"],
    "food_quality": [r"\bfood\b", r"\bquality\b"],
    "price_value": [r"\bprice\b", r"\bvalue\b"],
    "packaging": [r"\bpackaging\b"],
    "customer_support": [r"\bcustomer\b", r"\bsupport\b"],
    "restaurant_variety": [r"\brestaurant\b", r"\bvariety\b"],
    "app_experience": [r"\bapp\b", r"\bexperience\b"],
    "hygiene": [r"\bhygiene\b"],
}



def classify_with_keywords(doc_id: str, content: str) -> dict:
    """Classify a document using keyword patterns."""
    text = content.lower()

    # 1. Hesitation reasons
    hesitation_reasons = []
    for reason, patterns in HESITATION_PATTERNS.items():
        for pattern in patterns:
            m = re.search(pattern, text, re.IGNORECASE)
            if m:
                start = max(0, m.start() - 25)
                end = min(len(content), m.end() + 35)
                evidence = content[start:end].strip()
                hesitation_reasons.append({
                    "reason": reason,
                    "confidence": 0.85,
                    "evidence_quote": evidence,
                })
                break

    if not hesitation_reasons:
        hesitation_reasons.append({
            "reason": "delivery_delay_fear",
            "confidence": 0.50,
            "evidence_quote": content[:60],
        })

    # 2. Intent
    user_intent = "unknown"
    for intent, patterns in INTENT_PATTERNS.items():
        if any(re.search(p, text, re.IGNORECASE) for p in patterns):
            user_intent = intent
            break

    # 3. Platforms
    platforms = []
    for platform, patterns in PLATFORM_PATTERNS.items():
        if any(re.search(p, text, re.IGNORECASE) for p in patterns):
            platforms.append(platform)

    # 4. External info
    info_types = []
    for info_type, patterns in INFO_PATTERNS.items():
        if any(re.search(p, text, re.IGNORECASE) for p in patterns):
            info_types.append(info_type)

    # 5. Factor mentions
    factor_mentions = {}
    for factor, patterns in FACTOR_PATTERNS.items():
        mentioned = any(re.search(p, text, re.IGNORECASE) for p in patterns)
        sentiment = "neutral"
        if mentioned:
            if any(w in text for w in ["bad", "poor", "waste", "terrible", "worst", "hate", "slow", "fake"]):
                sentiment = "negative"
            elif any(w in text for w in ["good", "great", "nice", "love", "perfect", "worth", "fast", "best"]):
                sentiment = "positive"
        factor_mentions[factor] = {
            "mentioned": mentioned,
            "sentiment": sentiment,
        }

    # 6. Unmet needs (basic extraction)
    unmet_needs = []
    for r in hesitation_reasons[:2]:
        unmet_needs.append(f"Address {r['reason'].replace('_', ' ')}")
    if not unmet_needs:
        unmet_needs.append("Improve user experience")

    # 7. Question mapping
    q_map = [1]
    for r in hesitation_reasons:
        if r["reason"] in HESITATION_PATTERNS:
            q_map.extend([2, 3])
            break
    if platforms:
        q_map.append(5)
    if info_types:
        q_map.append(6)

    return {
        "doc_id": doc_id,
        "classification": {
            "hesitation_reasons": hesitation_reasons[:5],
            "user_intent": user_intent,
            "user_segment_signals": {
                "inferred_age_group": "unknown",
                "price_sensitivity": "unknown",
                "engagement_level": "unknown",
                "gender_signal": "unknown",
            },
            "comparison_behavior": {
                "compares_across_platforms": len(platforms) > 0,
                "platforms_mentioned": platforms,
                "comparison_criteria": ["price", "quality"] if platforms else [],
            },
            "external_info_seeking": {
                "seeks_external_info": len(info_types) > 0,
                "info_types": info_types,
            },
            "factor_mentions": factor_mentions,
            "unmet_needs": unmet_needs[:3],
            "brief_question_mapping": sorted(set(q_map)),
            "is_primary_signal": True,
        },
    }
