"""
Prompt templates for LLM classification.
Auto-generated by setup_engine.py — edit discovery_config.yaml to change.
"""

# ──────────────────────────────────────────────────────────
# System Prompt
# ──────────────────────────────────────────────────────────

SYSTEM_PROMPT = """You are an expert analyst classifying user feedback about Swiggy, a Food Delivery platform.

Your task: For each review/comment provided, extract structured classification tags using the JSON schema below. These tags will be aggregated to answer strategic business questions about user friction and hesitation.

CRITICAL RULES:
1. Respond ONLY with valid JSON. No markdown, no explanations, no extra text.
2. Many reviews are in Hinglish (Hindi-English code-mixed). Classify these with the same schema — do NOT skip them.
3. A single review can have MULTIPLE hesitation reasons, factor mentions, and unmet needs. Extract ALL that apply.
4. Only assign tags you are confident about. Use the "confidence" field (0.0–1.0) to express certainty.
5. Always include an "evidence_quote" — the exact substring from the review supporting each tag.
6. If a review has NO relevant signal for a field, use the default/empty value (e.g., "unknown", empty array).
7. Do NOT hallucinate or infer information not present in the text.
8. For "unmet_needs", extract the user's own words about what they wish existed — do not rephrase.

SCHEMA:
{
  "doc_id": "string — pass through from input",
  "classification": {
    "hesitation_reasons": [
      {
        "reason": "delivery_delay_fear | price_surge | food_quality_doubt | hygiene_concern | minimum_order_concern | restaurant_closed | payment_issue | address_issue | competitor_better_offer | portion_size_doubt | waiting_for_offer | meal_timing_mismatch | trust_deficit | customer_support_issue | packaging_concern | other",
        "confidence": 0.0-1.0,
        "evidence_quote": "exact substring from the review"
      }
    ],
    "user_intent": "genuine_order_intent | browsing | price_checking | comparison_shortlist | meal_planning | unknown",
    "user_segment_signals": {
      "inferred_age_group": "gen_z | millennial | gen_x | unknown",
      "price_sensitivity": "high | medium | low | unknown",
      "engagement_level": "high | casual | unknown",
      "gender_signal": "male | female | non_binary | unknown"
    },
    "comparison_behavior": {
      "compares_across_platforms": true | false,
      "platforms_mentioned": ["zomato", "eatsure", "uber_eats", "dunzo", "blinkit", "offline_restaurant", "other"],
      "comparison_criteria": ["price", "quality", "delivery", "variety", "other"]
    },
    "external_info_seeking": {
      "seeks_external_info": true | false,
      "info_types": ["youtube_reviews", "instagram_food", "google_search", "ask_friends", "google_maps_reviews", "food_blogger", "other"]
    },
    "factor_mentions": {
      "delivery_speed": { "mentioned": true | false, "sentiment": "positive | negative | neutral | mixed" },
      "food_quality": { "mentioned": true | false, "sentiment": "positive | negative | neutral | mixed" },
      "price_value": { "mentioned": true | false, "sentiment": "positive | negative | neutral | mixed" },
      "packaging": { "mentioned": true | false, "sentiment": "positive | negative | neutral | mixed" },
      "customer_support": { "mentioned": true | false, "sentiment": "positive | negative | neutral | mixed" },
      "restaurant_variety": { "mentioned": true | false, "sentiment": "positive | negative | neutral | mixed" },
      "app_experience": { "mentioned": true | false, "sentiment": "positive | negative | neutral | mixed" },
      "hygiene": { "mentioned": true | false, "sentiment": "positive | negative | neutral | mixed" }
    },
    "unmet_needs": ["free-text strings — extracted from the user's own words"],
    "brief_question_mapping": [1, 2, 7],
    "is_primary_signal": true | false
  }
}

QUESTION MAPPING REFERENCE:
Map each review to the relevant questions it helps answer (by number):
  1. Why do users open the app but abandon their cart before ordering?
  2. What prevents users from completing their food order?
  3. What uncertainties remain after selecting a restaurant?
  4. What causes users to postpone placing an order?
  5. How do users compare food delivery platforms before ordering?
  6. What information do users seek outside the app before ordering?
  7. What role do price, delivery speed, food quality, hygiene, packaging, and restaurant variety play?
  8. When is the cart genuine order intent vs casual browsing?
  9. How do friction patterns differ across user segments and platforms?
  10. What unmet needs emerge consistently across user feedback?"""


# ──────────────────────────────────────────────────────────
# Few-Shot Examples
# ──────────────────────────────────────────────────────────

FEW_SHOT_EXAMPLES = [
    # Example 1
    {
        "input": '[Document doc_001]: "Ordered biryani at 8pm, app said 30 min delivery. After 1.5 hours still waiting. Called the restaurant — they said Swiggy hasn't assigned a rider yet. Cancelled and ordered from Zomato instead, got it in 25 minutes."',
        "output": '{"doc_id": "doc_001", "classification": {"hesitation_reasons": [{"reason": "delivery_delay_fear", "confidence": 0.95, "evidence_quote": "After 1.5 hours still waiting"}, {"reason": "competitor_better_offer", "confidence": 0.85, "evidence_quote": "ordered from Zomato instead, got it in 25 minutes"}], "user_intent": "genuine_order_intent", "user_segment_signals": {"inferred_age_group": "millennial", "price_sensitivity": "medium", "engagement_level": "unknown", "gender_signal": "unknown"}, "comparison_behavior": {"compares_across_platforms": true, "platforms_mentioned": ["zomato"], "comparison_criteria": ["price"]}, "external_info_seeking": {"seeks_external_info": false, "info_types": []}, "factor_mentions": {"delivery_speed": {"mentioned": false, "sentiment": "neutral"}, "food_quality": {"mentioned": false, "sentiment": "neutral"}, "price_value": {"mentioned": false, "sentiment": "neutral"}, "packaging": {"mentioned": false, "sentiment": "neutral"}, "customer_support": {"mentioned": false, "sentiment": "neutral"}, "restaurant_variety": {"mentioned": false, "sentiment": "neutral"}, "app_experience": {"mentioned": false, "sentiment": "neutral"}, "hygiene": {"mentioned": false, "sentiment": "neutral"}}, "unmet_needs": ["Accurate delivery time estimates", "Faster rider assignment"], "brief_question_mapping": [], "is_primary_signal": true}}',
    },
    # Example 2
    {
        "input": '[Document doc_002]: "Surge pricing is insane during rain. Same order costs 150 more. Checking Zomato but prices similar. Will wait for the rain to stop and order later. Also applied coupon SWIGGY50 but it says expired."',
        "output": '{"doc_id": "doc_002", "classification": {"hesitation_reasons": [{"reason": "price_surge", "confidence": 0.92, "evidence_quote": "Surge pricing is insane during rain. Same order costs 150 more"}, {"reason": "waiting_for_offer", "confidence": 0.8, "evidence_quote": "Will wait for the rain to stop and order later"}], "user_intent": "price_checking", "user_segment_signals": {"inferred_age_group": "unknown", "price_sensitivity": "high", "engagement_level": "unknown", "gender_signal": "unknown"}, "comparison_behavior": {"compares_across_platforms": true, "platforms_mentioned": ["zomato"], "comparison_criteria": ["price"]}, "external_info_seeking": {"seeks_external_info": false, "info_types": []}, "factor_mentions": {"delivery_speed": {"mentioned": false, "sentiment": "neutral"}, "food_quality": {"mentioned": false, "sentiment": "neutral"}, "price_value": {"mentioned": false, "sentiment": "neutral"}, "packaging": {"mentioned": false, "sentiment": "neutral"}, "customer_support": {"mentioned": false, "sentiment": "neutral"}, "restaurant_variety": {"mentioned": false, "sentiment": "neutral"}, "app_experience": {"mentioned": false, "sentiment": "neutral"}, "hygiene": {"mentioned": false, "sentiment": "neutral"}}, "unmet_needs": ["Transparent surge pricing", "Working coupon codes"], "brief_question_mapping": [], "is_primary_signal": true}}',
    },
    # Example 3
    {
        "input": '[Document doc_003]: "App crashes every time I open it. Fix your app!!"',
        "output": '{"doc_id": "doc_003", "classification": {"hesitation_reasons": [], "user_intent": "unknown", "user_segment_signals": {"inferred_age_group": "unknown", "price_sensitivity": "unknown", "engagement_level": "unknown", "gender_signal": "unknown"}, "comparison_behavior": {"compares_across_platforms": false, "platforms_mentioned": [], "comparison_criteria": []}, "external_info_seeking": {"seeks_external_info": false, "info_types": []}, "factor_mentions": {"delivery_speed": {"mentioned": false, "sentiment": "neutral"}, "food_quality": {"mentioned": false, "sentiment": "neutral"}, "price_value": {"mentioned": false, "sentiment": "neutral"}, "packaging": {"mentioned": false, "sentiment": "neutral"}, "customer_support": {"mentioned": false, "sentiment": "neutral"}, "restaurant_variety": {"mentioned": false, "sentiment": "neutral"}, "app_experience": {"mentioned": false, "sentiment": "neutral"}, "hygiene": {"mentioned": false, "sentiment": "neutral"}}, "unmet_needs": ["Stable app experience"], "brief_question_mapping": [], "is_primary_signal": false}}',
    },
]


# ──────────────────────────────────────────────────────────
# Batch Request Formatter
# ──────────────────────────────────────────────────────────

def format_batch_prompt(documents: list) -> str:
    """Format a batch of documents into the user prompt."""
    parts = ["Classify the following reviews. Return a JSON array with one classification object per document.\n"]
    for doc in documents:
        doc_id = doc.get("doc_id", "unknown")
        content = doc.get("content", "")
        words = content.split()
        if len(words) > 500:
            content = " ".join(words[:500]) + " [truncated]"
        parts.append(f'[Document {doc_id}]: "{content}"')
    return "\n\n".join(parts)


def build_few_shot_messages() -> list:
    """Build few-shot message history for chat-based APIs."""
    messages = []
    for example in FEW_SHOT_EXAMPLES:
        messages.append({"role": "user", "content": example["input"]})
        messages.append({"role": "model", "content": example["output"]})
    return messages


def estimate_tokens(text: str) -> int:
    """Rough token estimate — ~4 chars per token."""
    return len(text) // 4
