"""
Pydantic models for the classification schema.
Auto-generated by setup_engine.py — edit discovery_config.yaml to change.
"""

from typing import List, Optional, Dict
from pydantic import BaseModel, Field


# ──────────────────────────────────────────────────────────
# Valid Enum Constants
# ──────────────────────────────────────────────────────────

VALID_HESITATION_REASONS = [
    "delivery_delay_fear",
    "price_surge",
    "food_quality_doubt",
    "hygiene_concern",
    "minimum_order_concern",
    "restaurant_closed",
    "payment_issue",
    "address_issue",
    "competitor_better_offer",
    "portion_size_doubt",
    "waiting_for_offer",
    "meal_timing_mismatch",
    "trust_deficit",
    "customer_support_issue",
    "packaging_concern",
    "other"
]

VALID_INTENTS = [
    "genuine_order_intent",
    "browsing",
    "price_checking",
    "comparison_shortlist",
    "meal_planning",
    "unknown"
]

VALID_AGE_GROUPS = ["gen_z", "millennial", "gen_x", "unknown"]

VALID_PRICE_SENSITIVITY = ["high", "medium", "low", "unknown"]

VALID_ENGAGEMENT = ["high", "casual", "unknown"]

VALID_GENDER_SIGNALS = ["male", "female", "non_binary", "unknown"]

VALID_SENTIMENTS = ["positive", "negative", "neutral", "mixed"]

VALID_PLATFORMS = [
    "zomato",
    "eatsure",
    "uber_eats",
    "dunzo",
    "blinkit",
    "offline_restaurant",
    "other"
]

VALID_COMPARISON_CRITERIA = ["price", "quality", "delivery", "variety", "authenticity", "other"]

VALID_INFO_TYPES = [
    "youtube_reviews",
    "instagram_food",
    "google_search",
    "ask_friends",
    "google_maps_reviews",
    "food_blogger",
    "other"
]

FACTOR_NAMES = [
    "delivery_speed",
    "food_quality",
    "price_value",
    "packaging",
    "customer_support",
    "restaurant_variety",
    "app_experience",
    "hygiene"
]


# ──────────────────────────────────────────────────────────
# Pydantic Models
# ──────────────────────────────────────────────────────────

class HesitationReason(BaseModel):
    """A single hesitation reason with confidence and evidence."""
    reason: str = "other"
    confidence: float = 0.5
    evidence_quote: str = ""


class UserSegmentSignals(BaseModel):
    """Inferred user segment signals."""
    inferred_age_group: str = "unknown"
    price_sensitivity: str = "unknown"
    engagement_level: str = "unknown"
    gender_signal: str = "unknown"


class ComparisonBehavior(BaseModel):
    """Cross-platform comparison behavior."""
    compares_across_platforms: bool = False
    platforms_mentioned: List[str] = Field(default_factory=list)
    comparison_criteria: List[str] = Field(default_factory=list)


class ExternalInfoSeeking(BaseModel):
    """External information seeking behavior."""
    seeks_external_info: bool = False
    info_types: List[str] = Field(default_factory=list)


class FactorMentionItem(BaseModel):
    """A single factor mention."""
    mentioned: bool = False
    sentiment: str = "neutral"


class FactorMentions(BaseModel):
    """All factor mentions."""
    delivery_speed: FactorMentionItem = Field(default_factory=FactorMentionItem)
    food_quality: FactorMentionItem = Field(default_factory=FactorMentionItem)
    price_value: FactorMentionItem = Field(default_factory=FactorMentionItem)
    packaging: FactorMentionItem = Field(default_factory=FactorMentionItem)
    customer_support: FactorMentionItem = Field(default_factory=FactorMentionItem)
    restaurant_variety: FactorMentionItem = Field(default_factory=FactorMentionItem)
    app_experience: FactorMentionItem = Field(default_factory=FactorMentionItem)
    hygiene: FactorMentionItem = Field(default_factory=FactorMentionItem)


class Classification(BaseModel):
    """Full classification output for a single document."""
    hesitation_reasons: List[HesitationReason] = Field(default_factory=list)
    user_intent: str = "unknown"
    user_segment_signals: UserSegmentSignals = Field(default_factory=UserSegmentSignals)
    comparison_behavior: ComparisonBehavior = Field(default_factory=ComparisonBehavior)
    external_info_seeking: ExternalInfoSeeking = Field(default_factory=ExternalInfoSeeking)
    factor_mentions: FactorMentions = Field(default_factory=FactorMentions)
    unmet_needs: List[str] = Field(default_factory=list)
    brief_question_mapping: List[int] = Field(default_factory=list)
    is_primary_signal: bool = False


class DocumentClassification(BaseModel):
    """Classification result for a single document (doc_id + classification)."""
    doc_id: str
    classification: Classification = Field(default_factory=Classification)


class ClassificationResult(BaseModel):
    """Wrapper for a batch of classification results."""
    results: List[DocumentClassification] = Field(default_factory=list)
    model_used: str = ""
    tier_used: str = ""
    errors: List[str] = Field(default_factory=list)


def empty_classification(doc_id: str) -> DocumentClassification:
    """Return a default empty classification for a document."""
    return DocumentClassification(
        doc_id=doc_id,
        classification=Classification(
            hesitation_reasons=[],
            user_intent="unknown",
            user_segment_signals=UserSegmentSignals(),
            comparison_behavior=ComparisonBehavior(),
            external_info_seeking=ExternalInfoSeeking(),
            factor_mentions=FactorMentions(),
            unmet_needs=[],
            brief_question_mapping=[],
            is_primary_signal=False,
        ),
    )
